/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tdd.unit.tests;

public class SampleApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SampleApp().getGreeting());
    }
}
